apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
  name: ext-hello-server
  namespace: default
spec:
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-server
  sessionAffinity: None
  type: LoadBalancer
