apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: debian
  name: debian
  namespace: temis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: debian
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debian
    spec:
      containers:
      - image: gcr.io/bexs-develop/debian
        env:
        - name: START_COMMAND
          value: APIS   
        imagePullPolicy: IfNotPresent
        name: debian
        command:
            - /bin/sh
            - -c
            - "echo $my_env_var && sleep 99d"      
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
