apiVersion: v1
kind: Service
metadata:
  labels:
    app: debian
  name: ext-debian
  namespace: temis
spec:
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: debian
  sessionAffinity: None
  type: LoadBalancer
